include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - "packages/**/*.g.dart"
#    - "packages/**/example/**"
    - "packages/instabug_private_views/example-hybrid-ios-app/**/**"


linter:
  rules:
    # Not necessary for our current APIs
    avoid_positional_boolean_parameters: false
    omit_local_variable_types: true
