include: package:lint/analysis_options_package.yaml

linter:
  rules:
    # Code Style
    sort_constructors_first: true
    prefer_single_quotes: true
    omit_local_variable_types: true

    # Disabled until we migrate to singleton pattern
    avoid_classes_with_only_static_members: false

    # Some public APIs require this (e.g. APM.setEnabled(bool))
    avoid_positional_boolean_parameters: false

    # Gives more info about internal vs external imports
    always_use_package_imports: false
    prefer_relative_imports: true

