include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - "apps/example/**"
    - "**/*.g.dart"

linter:
  rules:
    # Not necessary for our current APIs
    avoid_positional_boolean_parameters: false
    omit_local_variable_types: true
