version: 2
jobs:
   test:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter test
      - run: dart analyze --fatal-warnings lib
      - run: flutter pub publish --dry-run

   release:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: chmod +x release.sh
      - run: ./release.sh  

workflows:
  version: 2
  build-test:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - hold
          filters:
            branches:
              only: master      