// Mocks generated by Mockito 5.4.4 from annotations
// in instabug_flutter/test/utils/screen_render/instabug_screen_render_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:developer' as _i15;
import 'dart:ui' as _i5;

import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/gestures.dart' as _i7;
import 'package:flutter/rendering.dart' as _i8;
import 'package:flutter/scheduler.dart' as _i13;
import 'package:flutter/services.dart' as _i6;
import 'package:flutter/src/widgets/binding.dart' as _i12;
import 'package:flutter/src/widgets/focus_manager.dart' as _i4;
import 'package:flutter/src/widgets/framework.dart' as _i9;
import 'package:flutter/src/widgets/platform_menu_bar.dart' as _i2;
import 'package:instabug_flutter/src/generated/apm.api.g.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlatformMenuDelegate_1 extends _i1.SmartFake
    implements _i2.PlatformMenuDelegate {
  _FakePlatformMenuDelegate_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueNotifier_2<T> extends _i1.SmartFake
    implements _i3.ValueNotifier<T> {
  _FakeValueNotifier_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFocusManager_3 extends _i1.SmartFake implements _i4.FocusManager {
  _FakeFocusManager_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeSingletonFlutterWindow_4 extends _i1.SmartFake
    implements _i5.SingletonFlutterWindow {
  _FakeSingletonFlutterWindow_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlatformDispatcher_5 extends _i1.SmartFake
    implements _i5.PlatformDispatcher {
  _FakePlatformDispatcher_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHardwareKeyboard_6 extends _i1.SmartFake
    implements _i6.HardwareKeyboard {
  _FakeHardwareKeyboard_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeyEventManager_7 extends _i1.SmartFake
    implements _i6.KeyEventManager {
  _FakeKeyEventManager_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBinaryMessenger_8 extends _i1.SmartFake
    implements _i6.BinaryMessenger {
  _FakeBinaryMessenger_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelBuffers_9 extends _i1.SmartFake
    implements _i5.ChannelBuffers {
  _FakeChannelBuffers_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRestorationManager_10 extends _i1.SmartFake
    implements _i6.RestorationManager {
  _FakeRestorationManager_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePointerRouter_11 extends _i1.SmartFake implements _i7.PointerRouter {
  _FakePointerRouter_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGestureArenaManager_12 extends _i1.SmartFake
    implements _i7.GestureArenaManager {
  _FakeGestureArenaManager_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePointerSignalResolver_13 extends _i1.SmartFake
    implements _i7.PointerSignalResolver {
  _FakePointerSignalResolver_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSamplingClock_14 extends _i1.SmartFake implements _i7.SamplingClock {
  _FakeSamplingClock_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRenderView_15 extends _i1.SmartFake implements _i8.RenderView {
  _FakeRenderView_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeMouseTracker_16 extends _i1.SmartFake implements _i8.MouseTracker {
  _FakeMouseTracker_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccessibilityFeatures_17 extends _i1.SmartFake
    implements _i5.AccessibilityFeatures {
  _FakeAccessibilityFeatures_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_18 extends _i1.SmartFake implements _i9.Widget {
  _FakeWidget_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeFuture_19<T1> extends _i1.SmartFake implements _i10.Future<T1> {
  _FakeFuture_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeViewConfiguration_20 extends _i1.SmartFake
    implements _i8.ViewConfiguration {
  _FakeViewConfiguration_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSceneBuilder_21 extends _i1.SmartFake implements _i5.SceneBuilder {
  _FakeSceneBuilder_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePictureRecorder_22 extends _i1.SmartFake
    implements _i5.PictureRecorder {
  _FakePictureRecorder_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCanvas_23 extends _i1.SmartFake implements _i5.Canvas {
  _FakeCanvas_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSemanticsHandle_24 extends _i1.SmartFake
    implements _i8.SemanticsHandle {
  _FakeSemanticsHandle_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSemanticsUpdateBuilder_25 extends _i1.SmartFake
    implements _i5.SemanticsUpdateBuilder {
  _FakeSemanticsUpdateBuilder_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FrameTiming].
///
/// See the documentation for Mockito's code generation for more information.
class MockFrameTiming extends _i1.Mock implements _i5.FrameTiming {
  MockFrameTiming() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get buildDuration => (super.noSuchMethod(
        Invocation.getter(#buildDuration),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#buildDuration),
        ),
      ) as Duration);

  @override
  Duration get rasterDuration => (super.noSuchMethod(
        Invocation.getter(#rasterDuration),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#rasterDuration),
        ),
      ) as Duration);

  @override
  Duration get vsyncOverhead => (super.noSuchMethod(
        Invocation.getter(#vsyncOverhead),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#vsyncOverhead),
        ),
      ) as Duration);

  @override
  Duration get totalSpan => (super.noSuchMethod(
        Invocation.getter(#totalSpan),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#totalSpan),
        ),
      ) as Duration);

  @override
  int get layerCacheCount => (super.noSuchMethod(
        Invocation.getter(#layerCacheCount),
        returnValue: 0,
      ) as int);

  @override
  int get layerCacheBytes => (super.noSuchMethod(
        Invocation.getter(#layerCacheBytes),
        returnValue: 0,
      ) as int);

  @override
  double get layerCacheMegabytes => (super.noSuchMethod(
        Invocation.getter(#layerCacheMegabytes),
        returnValue: 0.0,
      ) as double);

  @override
  int get pictureCacheCount => (super.noSuchMethod(
        Invocation.getter(#pictureCacheCount),
        returnValue: 0,
      ) as int);

  @override
  int get pictureCacheBytes => (super.noSuchMethod(
        Invocation.getter(#pictureCacheBytes),
        returnValue: 0,
      ) as int);

  @override
  double get pictureCacheMegabytes => (super.noSuchMethod(
        Invocation.getter(#pictureCacheMegabytes),
        returnValue: 0.0,
      ) as double);

  @override
  int get frameNumber => (super.noSuchMethod(
        Invocation.getter(#frameNumber),
        returnValue: 0,
      ) as int);

  @override
  int timestampInMicroseconds(_i5.FramePhase? phase) => (super.noSuchMethod(
        Invocation.method(
          #timestampInMicroseconds,
          [phase],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [ApmHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockApmHostApi extends _i1.Mock implements _i11.ApmHostApi {
  MockApmHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> setEnabled(bool? arg_isEnabled) => (super.noSuchMethod(
        Invocation.method(
          #setEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> isEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isEnabled,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> setScreenLoadingEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setScreenLoadingEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> isScreenLoadingEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isScreenLoadingEnabled,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> setColdAppLaunchEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setColdAppLaunchEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setAutoUITraceEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutoUITraceEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<String?> startExecutionTrace(
    String? arg_id,
    String? arg_name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #startExecutionTrace,
          [
            arg_id,
            arg_name,
          ],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<void> startFlow(String? arg_name) => (super.noSuchMethod(
        Invocation.method(
          #startFlow,
          [arg_name],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setFlowAttribute(
    String? arg_name,
    String? arg_key,
    String? arg_value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFlowAttribute,
          [
            arg_name,
            arg_key,
            arg_value,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> endFlow(String? arg_name) => (super.noSuchMethod(
        Invocation.method(
          #endFlow,
          [arg_name],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setExecutionTraceAttribute(
    String? arg_id,
    String? arg_key,
    String? arg_value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setExecutionTraceAttribute,
          [
            arg_id,
            arg_key,
            arg_value,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> endExecutionTrace(String? arg_id) => (super.noSuchMethod(
        Invocation.method(
          #endExecutionTrace,
          [arg_id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> startUITrace(String? arg_name) => (super.noSuchMethod(
        Invocation.method(
          #startUITrace,
          [arg_name],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> endUITrace() => (super.noSuchMethod(
        Invocation.method(
          #endUITrace,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> endAppLaunch() => (super.noSuchMethod(
        Invocation.method(
          #endAppLaunch,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> networkLogAndroid(Map<String?, Object?>? arg_data) =>
      (super.noSuchMethod(
        Invocation.method(
          #networkLogAndroid,
          [arg_data],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> startCpUiTrace(
    String? arg_screenName,
    int? arg_microTimeStamp,
    int? arg_traceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #startCpUiTrace,
          [
            arg_screenName,
            arg_microTimeStamp,
            arg_traceId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> reportScreenLoadingCP(
    int? arg_startTimeStampMicro,
    int? arg_durationMicro,
    int? arg_uiTraceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportScreenLoadingCP,
          [
            arg_startTimeStampMicro,
            arg_durationMicro,
            arg_uiTraceId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> endScreenLoadingCP(
    int? arg_timeStampMicro,
    int? arg_uiTraceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #endScreenLoadingCP,
          [
            arg_timeStampMicro,
            arg_uiTraceId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> isEndScreenLoadingEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isEndScreenLoadingEnabled,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> isScreenRenderEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isScreenRenderEnabled,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<double> deviceRefreshRate() => (super.noSuchMethod(
        Invocation.method(
          #deviceRefreshRate,
          [],
        ),
        returnValue: _i10.Future<double>.value(0.0),
      ) as _i10.Future<double>);

  @override
  _i10.Future<void> setScreenRenderEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setScreenRenderEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [WidgetsBinding].
///
/// See the documentation for Mockito's code generation for more information.
class MockWidgetsBinding extends _i1.Mock implements _i12.WidgetsBinding {
  MockWidgetsBinding() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PlatformMenuDelegate get platformMenuDelegate => (super.noSuchMethod(
        Invocation.getter(#platformMenuDelegate),
        returnValue: _FakePlatformMenuDelegate_1(
          this,
          Invocation.getter(#platformMenuDelegate),
        ),
      ) as _i2.PlatformMenuDelegate);

  @override
  set platformMenuDelegate(_i2.PlatformMenuDelegate? _platformMenuDelegate) =>
      super.noSuchMethod(
        Invocation.setter(
          #platformMenuDelegate,
          _platformMenuDelegate,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get debugBuildingDirtyElements => (super.noSuchMethod(
        Invocation.getter(#debugBuildingDirtyElements),
        returnValue: false,
      ) as bool);

  @override
  set debugBuildingDirtyElements(bool? _debugBuildingDirtyElements) =>
      super.noSuchMethod(
        Invocation.setter(
          #debugBuildingDirtyElements,
          _debugBuildingDirtyElements,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get debugShowWidgetInspectorOverride => (super.noSuchMethod(
        Invocation.getter(#debugShowWidgetInspectorOverride),
        returnValue: false,
      ) as bool);

  @override
  set debugShowWidgetInspectorOverride(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #debugShowWidgetInspectorOverride,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ValueNotifier<bool> get debugShowWidgetInspectorOverrideNotifier =>
      (super.noSuchMethod(
        Invocation.getter(#debugShowWidgetInspectorOverrideNotifier),
        returnValue: _FakeValueNotifier_2<bool>(
          this,
          Invocation.getter(#debugShowWidgetInspectorOverrideNotifier),
        ),
      ) as _i3.ValueNotifier<bool>);

  @override
  _i3.ValueNotifier<bool> get debugWidgetInspectorSelectionOnTapEnabled =>
      (super.noSuchMethod(
        Invocation.getter(#debugWidgetInspectorSelectionOnTapEnabled),
        returnValue: _FakeValueNotifier_2<bool>(
          this,
          Invocation.getter(#debugWidgetInspectorSelectionOnTapEnabled),
        ),
      ) as _i3.ValueNotifier<bool>);

  @override
  _i4.FocusManager get focusManager => (super.noSuchMethod(
        Invocation.getter(#focusManager),
        returnValue: _FakeFocusManager_3(
          this,
          Invocation.getter(#focusManager),
        ),
      ) as _i4.FocusManager);

  @override
  bool get firstFrameRasterized => (super.noSuchMethod(
        Invocation.getter(#firstFrameRasterized),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> get waitUntilFirstFrameRasterized => (super.noSuchMethod(
        Invocation.getter(#waitUntilFirstFrameRasterized),
        returnValue: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  bool get debugDidSendFirstFrameEvent => (super.noSuchMethod(
        Invocation.getter(#debugDidSendFirstFrameEvent),
        returnValue: false,
      ) as bool);

  @override
  bool get framesEnabled => (super.noSuchMethod(
        Invocation.getter(#framesEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isRootWidgetAttached => (super.noSuchMethod(
        Invocation.getter(#isRootWidgetAttached),
        returnValue: false,
      ) as bool);

  @override
  _i5.SingletonFlutterWindow get window => (super.noSuchMethod(
        Invocation.getter(#window),
        returnValue: _FakeSingletonFlutterWindow_4(
          this,
          Invocation.getter(#window),
        ),
      ) as _i5.SingletonFlutterWindow);

  @override
  _i5.PlatformDispatcher get platformDispatcher => (super.noSuchMethod(
        Invocation.getter(#platformDispatcher),
        returnValue: _FakePlatformDispatcher_5(
          this,
          Invocation.getter(#platformDispatcher),
        ),
      ) as _i5.PlatformDispatcher);

  @override
  bool get locked => (super.noSuchMethod(
        Invocation.getter(#locked),
        returnValue: false,
      ) as bool);

  @override
  _i3.ValueNotifier<int?> get accessibilityFocus => (super.noSuchMethod(
        Invocation.getter(#accessibilityFocus),
        returnValue: _FakeValueNotifier_2<int?>(
          this,
          Invocation.getter(#accessibilityFocus),
        ),
      ) as _i3.ValueNotifier<int?>);

  @override
  _i6.HardwareKeyboard get keyboard => (super.noSuchMethod(
        Invocation.getter(#keyboard),
        returnValue: _FakeHardwareKeyboard_6(
          this,
          Invocation.getter(#keyboard),
        ),
      ) as _i6.HardwareKeyboard);

  @override
  _i6.KeyEventManager get keyEventManager => (super.noSuchMethod(
        Invocation.getter(#keyEventManager),
        returnValue: _FakeKeyEventManager_7(
          this,
          Invocation.getter(#keyEventManager),
        ),
      ) as _i6.KeyEventManager);

  @override
  _i6.BinaryMessenger get defaultBinaryMessenger => (super.noSuchMethod(
        Invocation.getter(#defaultBinaryMessenger),
        returnValue: _FakeBinaryMessenger_8(
          this,
          Invocation.getter(#defaultBinaryMessenger),
        ),
      ) as _i6.BinaryMessenger);

  @override
  _i5.ChannelBuffers get channelBuffers => (super.noSuchMethod(
        Invocation.getter(#channelBuffers),
        returnValue: _FakeChannelBuffers_9(
          this,
          Invocation.getter(#channelBuffers),
        ),
      ) as _i5.ChannelBuffers);

  @override
  _i6.RestorationManager get restorationManager => (super.noSuchMethod(
        Invocation.getter(#restorationManager),
        returnValue: _FakeRestorationManager_10(
          this,
          Invocation.getter(#restorationManager),
        ),
      ) as _i6.RestorationManager);

  @override
  _i13.SchedulingStrategy get schedulingStrategy => (super.noSuchMethod(
        Invocation.getter(#schedulingStrategy),
        returnValue: ({
          required int priority,
          required _i13.SchedulerBinding scheduler,
        }) =>
            false,
      ) as _i13.SchedulingStrategy);

  @override
  set schedulingStrategy(_i13.SchedulingStrategy? _schedulingStrategy) =>
      super.noSuchMethod(
        Invocation.setter(
          #schedulingStrategy,
          _schedulingStrategy,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get transientCallbackCount => (super.noSuchMethod(
        Invocation.getter(#transientCallbackCount),
        returnValue: 0,
      ) as int);

  @override
  _i10.Future<void> get endOfFrame => (super.noSuchMethod(
        Invocation.getter(#endOfFrame),
        returnValue: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  bool get hasScheduledFrame => (super.noSuchMethod(
        Invocation.getter(#hasScheduledFrame),
        returnValue: false,
      ) as bool);

  @override
  _i13.SchedulerPhase get schedulerPhase => (super.noSuchMethod(
        Invocation.getter(#schedulerPhase),
        returnValue: _i13.SchedulerPhase.idle,
      ) as _i13.SchedulerPhase);

  @override
  Duration get currentFrameTimeStamp => (super.noSuchMethod(
        Invocation.getter(#currentFrameTimeStamp),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#currentFrameTimeStamp),
        ),
      ) as Duration);

  @override
  Duration get currentSystemFrameTimeStamp => (super.noSuchMethod(
        Invocation.getter(#currentSystemFrameTimeStamp),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#currentSystemFrameTimeStamp),
        ),
      ) as Duration);

  @override
  _i7.PointerRouter get pointerRouter => (super.noSuchMethod(
        Invocation.getter(#pointerRouter),
        returnValue: _FakePointerRouter_11(
          this,
          Invocation.getter(#pointerRouter),
        ),
      ) as _i7.PointerRouter);

  @override
  _i7.GestureArenaManager get gestureArena => (super.noSuchMethod(
        Invocation.getter(#gestureArena),
        returnValue: _FakeGestureArenaManager_12(
          this,
          Invocation.getter(#gestureArena),
        ),
      ) as _i7.GestureArenaManager);

  @override
  _i7.PointerSignalResolver get pointerSignalResolver => (super.noSuchMethod(
        Invocation.getter(#pointerSignalResolver),
        returnValue: _FakePointerSignalResolver_13(
          this,
          Invocation.getter(#pointerSignalResolver),
        ),
      ) as _i7.PointerSignalResolver);

  @override
  bool get resamplingEnabled => (super.noSuchMethod(
        Invocation.getter(#resamplingEnabled),
        returnValue: false,
      ) as bool);

  @override
  set resamplingEnabled(bool? _resamplingEnabled) => super.noSuchMethod(
        Invocation.setter(
          #resamplingEnabled,
          _resamplingEnabled,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Duration get samplingOffset => (super.noSuchMethod(
        Invocation.getter(#samplingOffset),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#samplingOffset),
        ),
      ) as Duration);

  @override
  set samplingOffset(Duration? _samplingOffset) => super.noSuchMethod(
        Invocation.setter(
          #samplingOffset,
          _samplingOffset,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.SamplingClock get samplingClock => (super.noSuchMethod(
        Invocation.getter(#samplingClock),
        returnValue: _FakeSamplingClock_14(
          this,
          Invocation.getter(#samplingClock),
        ),
      ) as _i7.SamplingClock);

  @override
  _i8.PipelineOwner get pipelineOwner => (super.noSuchMethod(
        Invocation.getter(#pipelineOwner),
        returnValue: _i14.dummyValue<_i8.PipelineOwner>(
          this,
          Invocation.getter(#pipelineOwner),
        ),
      ) as _i8.PipelineOwner);

  @override
  _i8.RenderView get renderView => (super.noSuchMethod(
        Invocation.getter(#renderView),
        returnValue: _FakeRenderView_15(
          this,
          Invocation.getter(#renderView),
        ),
      ) as _i8.RenderView);

  @override
  _i8.MouseTracker get mouseTracker => (super.noSuchMethod(
        Invocation.getter(#mouseTracker),
        returnValue: _FakeMouseTracker_16(
          this,
          Invocation.getter(#mouseTracker),
        ),
      ) as _i8.MouseTracker);

  @override
  _i8.PipelineOwner get rootPipelineOwner => (super.noSuchMethod(
        Invocation.getter(#rootPipelineOwner),
        returnValue: _i14.dummyValue<_i8.PipelineOwner>(
          this,
          Invocation.getter(#rootPipelineOwner),
        ),
      ) as _i8.PipelineOwner);

  @override
  Iterable<_i8.RenderView> get renderViews => (super.noSuchMethod(
        Invocation.getter(#renderViews),
        returnValue: <_i8.RenderView>[],
      ) as Iterable<_i8.RenderView>);

  @override
  bool get sendFramesToEngine => (super.noSuchMethod(
        Invocation.getter(#sendFramesToEngine),
        returnValue: false,
      ) as bool);

  @override
  bool get semanticsEnabled => (super.noSuchMethod(
        Invocation.getter(#semanticsEnabled),
        returnValue: false,
      ) as bool);

  @override
  int get debugOutstandingSemanticsHandles => (super.noSuchMethod(
        Invocation.getter(#debugOutstandingSemanticsHandles),
        returnValue: 0,
      ) as int);

  @override
  _i5.AccessibilityFeatures get accessibilityFeatures => (super.noSuchMethod(
        Invocation.getter(#accessibilityFeatures),
        returnValue: _FakeAccessibilityFeatures_17(
          this,
          Invocation.getter(#accessibilityFeatures),
        ),
      ) as _i5.AccessibilityFeatures);

  @override
  bool get disableAnimations => (super.noSuchMethod(
        Invocation.getter(#disableAnimations),
        returnValue: false,
      ) as bool);

  @override
  void initInstances() => super.noSuchMethod(
        Invocation.method(
          #initInstances,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetInternalState() => super.noSuchMethod(
        Invocation.method(
          #resetInternalState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void initServiceExtensions() => super.noSuchMethod(
        Invocation.method(
          #initServiceExtensions,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addObserver(_i12.WidgetsBindingObserver? observer) => super.noSuchMethod(
        Invocation.method(
          #addObserver,
          [observer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool removeObserver(_i12.WidgetsBindingObserver? observer) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeObserver,
          [observer],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<_i5.AppExitResponse> handleRequestAppExit() =>
      (super.noSuchMethod(
        Invocation.method(
          #handleRequestAppExit,
          [],
        ),
        returnValue:
            _i10.Future<_i5.AppExitResponse>.value(_i5.AppExitResponse.exit),
      ) as _i10.Future<_i5.AppExitResponse>);

  @override
  void handleMetricsChanged() => super.noSuchMethod(
        Invocation.method(
          #handleMetricsChanged,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleTextScaleFactorChanged() => super.noSuchMethod(
        Invocation.method(
          #handleTextScaleFactorChanged,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handlePlatformBrightnessChanged() => super.noSuchMethod(
        Invocation.method(
          #handlePlatformBrightnessChanged,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleAccessibilityFeaturesChanged() => super.noSuchMethod(
        Invocation.method(
          #handleAccessibilityFeaturesChanged,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleLocaleChanged() => super.noSuchMethod(
        Invocation.method(
          #handleLocaleChanged,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchLocalesChanged(List<_i5.Locale>? locales) => super.noSuchMethod(
        Invocation.method(
          #dispatchLocalesChanged,
          [locales],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchAccessibilityFeaturesChanged() => super.noSuchMethod(
        Invocation.method(
          #dispatchAccessibilityFeaturesChanged,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<bool> handlePopRoute() => (super.noSuchMethod(
        Invocation.method(
          #handlePopRoute,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> handlePushRoute(String? route) => (super.noSuchMethod(
        Invocation.method(
          #handlePushRoute,
          [route],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  void handleAppLifecycleStateChanged(_i5.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #handleAppLifecycleStateChanged,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleViewFocusChanged(_i5.ViewFocusEvent? event) => super.noSuchMethod(
        Invocation.method(
          #handleViewFocusChanged,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleMemoryPressure() => super.noSuchMethod(
        Invocation.method(
          #handleMemoryPressure,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void drawFrame() => super.noSuchMethod(
        Invocation.method(
          #drawFrame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Widget wrapWithDefaultView(_i9.Widget? rootWidget) => (super.noSuchMethod(
        Invocation.method(
          #wrapWithDefaultView,
          [rootWidget],
        ),
        returnValue: _FakeWidget_18(
          this,
          Invocation.method(
            #wrapWithDefaultView,
            [rootWidget],
          ),
        ),
      ) as _i9.Widget);

  @override
  void scheduleAttachRootWidget(_i9.Widget? rootWidget) => super.noSuchMethod(
        Invocation.method(
          #scheduleAttachRootWidget,
          [rootWidget],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void attachRootWidget(_i9.Widget? rootWidget) => super.noSuchMethod(
        Invocation.method(
          #attachRootWidget,
          [rootWidget],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void attachToBuildOwner(_i12.RootWidget? widget) => super.noSuchMethod(
        Invocation.method(
          #attachToBuildOwner,
          [widget],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> performReassemble() => (super.noSuchMethod(
        Invocation.method(
          #performReassemble,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i5.Locale? computePlatformResolvedLocale(
          List<_i5.Locale>? supportedLocales) =>
      (super.noSuchMethod(Invocation.method(
        #computePlatformResolvedLocale,
        [supportedLocales],
      )) as _i5.Locale?);

  @override
  bool debugCheckZone(String? entryPoint) => (super.noSuchMethod(
        Invocation.method(
          #debugCheckZone,
          [entryPoint],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> lockEvents(_i10.Future<void> Function()? callback) =>
      (super.noSuchMethod(
        Invocation.method(
          #lockEvents,
          [callback],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void unlocked() => super.noSuchMethod(
        Invocation.method(
          #unlocked,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> reassembleApplication() => (super.noSuchMethod(
        Invocation.method(
          #reassembleApplication,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void registerSignalServiceExtension({
    required String? name,
    required _i3.AsyncCallback? callback,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerSignalServiceExtension,
          [],
          {
            #name: name,
            #callback: callback,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerBoolServiceExtension({
    required String? name,
    required _i3.AsyncValueGetter<bool>? getter,
    required _i3.AsyncValueSetter<bool>? setter,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerBoolServiceExtension,
          [],
          {
            #name: name,
            #getter: getter,
            #setter: setter,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerNumericServiceExtension({
    required String? name,
    required _i3.AsyncValueGetter<double>? getter,
    required _i3.AsyncValueSetter<double>? setter,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerNumericServiceExtension,
          [],
          {
            #name: name,
            #getter: getter,
            #setter: setter,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void postEvent(
    String? eventKind,
    Map<String, dynamic>? eventData,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #postEvent,
          [
            eventKind,
            eventData,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerStringServiceExtension({
    required String? name,
    required _i3.AsyncValueGetter<String>? getter,
    required _i3.AsyncValueSetter<String>? setter,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerStringServiceExtension,
          [],
          {
            #name: name,
            #getter: getter,
            #setter: setter,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerServiceExtension({
    required String? name,
    required _i3.ServiceExtensionCallback? callback,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerServiceExtension,
          [],
          {
            #name: name,
            #callback: callback,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.BinaryMessenger createBinaryMessenger() => (super.noSuchMethod(
        Invocation.method(
          #createBinaryMessenger,
          [],
        ),
        returnValue: _FakeBinaryMessenger_8(
          this,
          Invocation.method(
            #createBinaryMessenger,
            [],
          ),
        ),
      ) as _i6.BinaryMessenger);

  @override
  _i10.Future<void> handleSystemMessage(Object? systemMessage) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleSystemMessage,
          [systemMessage],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void initLicenses() => super.noSuchMethod(
        Invocation.method(
          #initLicenses,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void evict(String? asset) => super.noSuchMethod(
        Invocation.method(
          #evict,
          [asset],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void readInitialLifecycleStateFromNativeWindow() => super.noSuchMethod(
        Invocation.method(
          #readInitialLifecycleStateFromNativeWindow,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i5.AppExitResponse> exitApplication(
    _i5.AppExitType? exitType, [
    int? exitCode = 0,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #exitApplication,
          [
            exitType,
            exitCode,
          ],
        ),
        returnValue:
            _i10.Future<_i5.AppExitResponse>.value(_i5.AppExitResponse.exit),
      ) as _i10.Future<_i5.AppExitResponse>);

  @override
  _i6.RestorationManager createRestorationManager() => (super.noSuchMethod(
        Invocation.method(
          #createRestorationManager,
          [],
        ),
        returnValue: _FakeRestorationManager_10(
          this,
          Invocation.method(
            #createRestorationManager,
            [],
          ),
        ),
      ) as _i6.RestorationManager);

  @override
  void setSystemUiChangeCallback(_i6.SystemUiChangeCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #setSystemUiChangeCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> initializationComplete() => (super.noSuchMethod(
        Invocation.method(
          #initializationComplete,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void addTimingsCallback(_i5.TimingsCallback? callback) => super.noSuchMethod(
        Invocation.method(
          #addTimingsCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeTimingsCallback(_i5.TimingsCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #removeTimingsCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<T> scheduleTask<T>(
    _i13.TaskCallback<T>? task,
    _i13.Priority? priority, {
    String? debugLabel,
    _i15.Flow? flow,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleTask,
          [
            task,
            priority,
          ],
          {
            #debugLabel: debugLabel,
            #flow: flow,
          },
        ),
        returnValue: _i14.ifNotNull(
              _i14.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #scheduleTask,
                  [
                    task,
                    priority,
                  ],
                  {
                    #debugLabel: debugLabel,
                    #flow: flow,
                  },
                ),
              ),
              (T v) => _i10.Future<T>.value(v),
            ) ??
            _FakeFuture_19<T>(
              this,
              Invocation.method(
                #scheduleTask,
                [
                  task,
                  priority,
                ],
                {
                  #debugLabel: debugLabel,
                  #flow: flow,
                },
              ),
            ),
      ) as _i10.Future<T>);

  @override
  bool handleEventLoopCallback() => (super.noSuchMethod(
        Invocation.method(
          #handleEventLoopCallback,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  int scheduleFrameCallback(
    _i13.FrameCallback? callback, {
    bool? rescheduling = false,
    bool? scheduleNewFrame = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleFrameCallback,
          [callback],
          {
            #rescheduling: rescheduling,
            #scheduleNewFrame: scheduleNewFrame,
          },
        ),
        returnValue: 0,
      ) as int);

  @override
  void cancelFrameCallbackWithId(int? id) => super.noSuchMethod(
        Invocation.method(
          #cancelFrameCallbackWithId,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool debugAssertNoTransientCallbacks(String? reason) => (super.noSuchMethod(
        Invocation.method(
          #debugAssertNoTransientCallbacks,
          [reason],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool debugAssertNoPendingPerformanceModeRequests(String? reason) =>
      (super.noSuchMethod(
        Invocation.method(
          #debugAssertNoPendingPerformanceModeRequests,
          [reason],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool debugAssertNoTimeDilation(String? reason) => (super.noSuchMethod(
        Invocation.method(
          #debugAssertNoTimeDilation,
          [reason],
        ),
        returnValue: false,
      ) as bool);

  @override
  void addPersistentFrameCallback(_i13.FrameCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #addPersistentFrameCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addPostFrameCallback(
    _i13.FrameCallback? callback, {
    String? debugLabel = r'callback',
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addPostFrameCallback,
          [callback],
          {#debugLabel: debugLabel},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void ensureFrameCallbacksRegistered() => super.noSuchMethod(
        Invocation.method(
          #ensureFrameCallbacksRegistered,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void ensureVisualUpdate() => super.noSuchMethod(
        Invocation.method(
          #ensureVisualUpdate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void scheduleFrame() => super.noSuchMethod(
        Invocation.method(
          #scheduleFrame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void scheduleForcedFrame() => super.noSuchMethod(
        Invocation.method(
          #scheduleForcedFrame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void scheduleWarmUpFrame() => super.noSuchMethod(
        Invocation.method(
          #scheduleWarmUpFrame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetEpoch() => super.noSuchMethod(
        Invocation.method(
          #resetEpoch,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleBeginFrame(Duration? rawTimeStamp) => super.noSuchMethod(
        Invocation.method(
          #handleBeginFrame,
          [rawTimeStamp],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.PerformanceModeRequestHandle? requestPerformanceMode(
          _i5.DartPerformanceMode? mode) =>
      (super.noSuchMethod(Invocation.method(
        #requestPerformanceMode,
        [mode],
      )) as _i13.PerformanceModeRequestHandle?);

  @override
  void handleDrawFrame() => super.noSuchMethod(
        Invocation.method(
          #handleDrawFrame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cancelPointer(int? pointer) => super.noSuchMethod(
        Invocation.method(
          #cancelPointer,
          [pointer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handlePointerEvent(_i6.PointerEvent? event) => super.noSuchMethod(
        Invocation.method(
          #handlePointerEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hitTestInView(
    _i7.HitTestResult? result,
    _i5.Offset? position,
    int? viewId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #hitTestInView,
          [
            result,
            position,
            viewId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hitTest(
    _i7.HitTestResult? result,
    _i5.Offset? position,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #hitTest,
          [
            result,
            position,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchEvent(
    _i6.PointerEvent? event,
    _i7.HitTestResult? hitTestResult,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchEvent,
          [
            event,
            hitTestResult,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleEvent(
    _i6.PointerEvent? event,
    _i7.HitTestEntry<_i7.HitTestTarget>? entry,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #handleEvent,
          [
            event,
            entry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetGestureBinding() => super.noSuchMethod(
        Invocation.method(
          #resetGestureBinding,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.PipelineOwner createRootPipelineOwner() => (super.noSuchMethod(
        Invocation.method(
          #createRootPipelineOwner,
          [],
        ),
        returnValue: _i14.dummyValue<_i8.PipelineOwner>(
          this,
          Invocation.method(
            #createRootPipelineOwner,
            [],
          ),
        ),
      ) as _i8.PipelineOwner);

  @override
  void addRenderView(_i8.RenderView? view) => super.noSuchMethod(
        Invocation.method(
          #addRenderView,
          [view],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeRenderView(_i8.RenderView? view) => super.noSuchMethod(
        Invocation.method(
          #removeRenderView,
          [view],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.ViewConfiguration createViewConfigurationFor(
          _i8.RenderView? renderView) =>
      (super.noSuchMethod(
        Invocation.method(
          #createViewConfigurationFor,
          [renderView],
        ),
        returnValue: _FakeViewConfiguration_20(
          this,
          Invocation.method(
            #createViewConfigurationFor,
            [renderView],
          ),
        ),
      ) as _i8.ViewConfiguration);

  @override
  _i5.SceneBuilder createSceneBuilder() => (super.noSuchMethod(
        Invocation.method(
          #createSceneBuilder,
          [],
        ),
        returnValue: _FakeSceneBuilder_21(
          this,
          Invocation.method(
            #createSceneBuilder,
            [],
          ),
        ),
      ) as _i5.SceneBuilder);

  @override
  _i5.PictureRecorder createPictureRecorder() => (super.noSuchMethod(
        Invocation.method(
          #createPictureRecorder,
          [],
        ),
        returnValue: _FakePictureRecorder_22(
          this,
          Invocation.method(
            #createPictureRecorder,
            [],
          ),
        ),
      ) as _i5.PictureRecorder);

  @override
  _i5.Canvas createCanvas(_i5.PictureRecorder? recorder) => (super.noSuchMethod(
        Invocation.method(
          #createCanvas,
          [recorder],
        ),
        returnValue: _FakeCanvas_23(
          this,
          Invocation.method(
            #createCanvas,
            [recorder],
          ),
        ),
      ) as _i5.Canvas);

  @override
  void initMouseTracker([_i8.MouseTracker? tracker]) => super.noSuchMethod(
        Invocation.method(
          #initMouseTracker,
          [tracker],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void performSemanticsAction(_i5.SemanticsActionEvent? action) =>
      super.noSuchMethod(
        Invocation.method(
          #performSemanticsAction,
          [action],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deferFirstFrame() => super.noSuchMethod(
        Invocation.method(
          #deferFirstFrame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void allowFirstFrame() => super.noSuchMethod(
        Invocation.method(
          #allowFirstFrame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetFirstFrameSent() => super.noSuchMethod(
        Invocation.method(
          #resetFirstFrameSent,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addSemanticsEnabledListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addSemanticsEnabledListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeSemanticsEnabledListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeSemanticsEnabledListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addSemanticsActionListener(
          _i3.ValueSetter<_i5.SemanticsActionEvent>? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addSemanticsActionListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeSemanticsActionListener(
          _i3.ValueSetter<_i5.SemanticsActionEvent>? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeSemanticsActionListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.SemanticsHandle ensureSemantics() => (super.noSuchMethod(
        Invocation.method(
          #ensureSemantics,
          [],
        ),
        returnValue: _FakeSemanticsHandle_24(
          this,
          Invocation.method(
            #ensureSemantics,
            [],
          ),
        ),
      ) as _i8.SemanticsHandle);

  @override
  _i5.SemanticsUpdateBuilder createSemanticsUpdateBuilder() =>
      (super.noSuchMethod(
        Invocation.method(
          #createSemanticsUpdateBuilder,
          [],
        ),
        returnValue: _FakeSemanticsUpdateBuilder_25(
          this,
          Invocation.method(
            #createSemanticsUpdateBuilder,
            [],
          ),
        ),
      ) as _i5.SemanticsUpdateBuilder);
}
