name: instabug_private_views
description: "An extension for the Instabug Flutter SDK that enables support for masking private views during screen capturing."
version: 1.0.0
homepage: https://www.instabug.com
repository: https://github.com/Instabug/Instabug-Flutter
documentation: https://docs.instabug.com/docs/flutter-overview

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  instabug_flutter:

dev_dependencies:
  build_runner: ^2.0.3
  fake_async: '>=1.2.0 <1.4.0'
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  # mockito v5.2.0 is needed for running Flutter 2 tests on CI
  mockito: '>=5.2.0 <5.5.0'
  pana: ^0.21.0
  # pigeon v3.0.0 is needed for running Flutter 2 tests on CI
  pigeon: '>=3.0.0 <=10.1.5'

flutter:
  plugin:
    platforms:
      android:
        package: com.instabug.instabug_private_views
        pluginClass: InstabugPrivateViewsPlugin
      ios:
        pluginClass: InstabugPrivateViewsPlugin