name: instabug_private_views
description: "An add-on for the Instabug Flutter SDK that provides private views support in screen capturing."
version: 1.0.0
homepage: https://www.instabug.com

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  instabug_flutter:
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.0.3
  fake_async: '>=1.2.0 <1.4.0'
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  # mockito v5.2.0 is needed for running Flutter 2 tests on CI
  mockito: '>=5.2.0 <5.5.0'
  pana: ^0.21.0
  # pigeon v3.0.0 is needed for running Flutter 2 tests on CI
  pigeon: '>=3.0.0 <=10.1.5'
