version: 2
jobs:
   test:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
      - run: flutter analyze .
      - run: flutter pub publish --dry-run
      
   release:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: ./release.sh

workflows:
  version: 2
  build-test:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - hold
          filters:
            branches:
              only: master
